spring.application.name=digitrans-api
server.port=8080

# Configuration MySQL (Dev Local / Production fallback)
spring.datasource.url=jdbc:mysql://localhost:3306/digitransdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuration JWT (Clé secrète robuste de 256 bits minimum)
app.jwt.secret=DigitransSecretKey2026VeryLongAndSecureKeyForJWTDigitransSecretKey2026VeryLongAndSecureKeyForJWT
app.jwt.expiration=86400000

# Configuration Blockchain Web3j
blockchain.node.url=http://localhost:8545
blockchain.contract.address=${BLOCKCHAIN_CONTRACT_ADDRESS:0x4858b9E6b1981F4C5bf02A4fFE5579DbAbe5E271}
