apiVersion: v1
kind: Service
metadata:
  name: digitrans-backend
spec:
  # Utilisation de NodePort pour exposer l'application sur l'EC2 (port hôte 30080)
  type: NodePort
  selector:
    app: digitrans-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
